//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoYogaToolkit.Lib.Automation.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoYogaToolkit.Lib.Automation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 When AC power adapter is connected 的本地化字符串。
        /// </summary>
        public static string ACAdapterConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ACAdapterConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When AC power adapter is disconnected 的本地化字符串。
        /// </summary>
        public static string ACAdapterDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ACAdapterDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kill apps 的本地化字符串。
        /// </summary>
        public static string DeactivateGPUAutomationStepState_KillApps {
            get {
                return ResourceManager.GetString("DeactivateGPUAutomationStepState_KillApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart GPU 的本地化字符串。
        /// </summary>
        public static string DeactivateGPUAutomationStepState_RestartGPU {
            get {
                return ResourceManager.GetString("DeactivateGPUAutomationStepState_RestartGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} second 的本地化字符串。
        /// </summary>
        public static string Delay_Second {
            get {
                return ResourceManager.GetString("Delay_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds 的本地化字符串。
        /// </summary>
        public static string Delay_Second_Many {
            get {
                return ResourceManager.GetString("Delay_Second_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When displays turn off 的本地化字符串。
        /// </summary>
        public static string DisplayOffAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DisplayOffAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When displays turn on 的本地化字符串。
        /// </summary>
        public static string DisplayOnAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DisplayOnAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When external display is connected 的本地化字符串。
        /// </summary>
        public static string ExternalDisplayConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ExternalDisplayConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When external display is disconnected 的本地化字符串。
        /// </summary>
        public static string ExternalDisplayDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ExternalDisplayDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When game is running 的本地化字符串。
        /// </summary>
        public static string GamesAreRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("GamesAreRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When game closes 的本地化字符串。
        /// </summary>
        public static string GamesStopAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("GamesStopAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lid closed 的本地化字符串。
        /// </summary>
        public static string LidClosedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LidClosedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lid opened 的本地化字符串。
        /// </summary>
        public static string LidOpenedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LidOpenedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When low wattage AC power adapter is connected 的本地化字符串。
        /// </summary>
        public static string LowWattageACAdapterConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LowWattageACAdapterConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On startup 的本地化字符串。
        /// </summary>
        public static string OnStartupAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("OnStartupAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When Power Mode is changed 的本地化字符串。
        /// </summary>
        public static string PowerModeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("PowerModeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When app starts 的本地化字符串。
        /// </summary>
        public static string ProcessesAreRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ProcessesAreRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When app closes 的本地化字符串。
        /// </summary>
        public static string ProcessesStopRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ProcessesStopRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At specified time 的本地化字符串。
        /// </summary>
        public static string TimeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("TimeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
    }
}
