//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoYogaToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoYogaToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_Custom {
            get {
                return ResourceManager.GetString("AccentColorSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string AccentColorSource_System {
            get {
                return ResourceManager.GetString("AccentColorSource_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, always 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, when sleeping 的本地化字符串。
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acrylic 的本地化字符串。
        /// </summary>
        public static string AppBackground_Acrylic {
            get {
                return ResourceManager.GetString("AppBackground_Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica 的本地化字符串。
        /// </summary>
        public static string AppBackground_Mica {
            get {
                return ResourceManager.GetString("AppBackground_Mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Disabled {
            get {
                return ResourceManager.GetString("AutorunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string AutorunState_Enabled {
            get {
                return ResourceManager.GetString("AutorunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled, delayed 的本地化字符串。
        /// </summary>
        public static string AutorunState_EnabledDelayed {
            get {
                return ResourceManager.GetString("AutorunState_EnabledDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conservation 的本地化字符串。
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rapid Charge 的本地化字符串。
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered Off 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered On 的本地化字符串。
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid 的本地化字符串。
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-Auto 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid-iGPU 的本地化字符串。
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_BottomRight {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_Center {
            get {
                return ResourceManager.GetString("NotificationPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_CenterRight {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top center 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top left 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top right 的本地化字符串。
        /// </summary>
        public static string NotificationPosition_TopRight {
            get {
                return ResourceManager.GetString("NotificationPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quiet 的本地化字符串。
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Auto {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
    }
}
